### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by Elizabeth1998** [Flimsyware/KentEvent#18]
Establish how to download Python and use PythonAnywhere

**Comment by sohamt09** [comment]
Python can be downloaded from https://www.python.org/downloads/ 
To use PythonAnywhere you need to sign up for a free plan on PythonAnywhere.After signing up and logging in go to the console menu item and click Bash. You can then make directory and work on it.

**Comment by Elizabeth1998** [comment]
Hello! I am going to post how to access python and its links in the Wiki
