### ISSUE TITLE
Database Schema wiki page

### ISSUE THREAD

**Issue by LouMayans** [Flimsyware/KentEvent#29]
-Set up all the tables in the database wiki page and make sure that the tables actually run in MySQL in pythonAnywhere

**Comment by mdunca14** [comment]
Added SQL for making event and university tables to the wiki

**Comment by LouMayans** [comment]
Created User table sheet then @mkozak2 will get the okay from the database and will add it to the wiki.

**Comment by mkozak2** [comment]
Added SQL for making user table to the wiki
