### ISSUE TITLE
Establish a vision statement

### ISSUE THREAD

**Issue by Elizabeth1998** [Flimsyware/KentEvent#3]
Look at example vision statements and create one that embodies the company

**Comment by mdunca14** [comment]
Later today or tomorrow, I will start looking around for some longer vision statements and post some examples we can work from.  DeLozier said the vision statement should be about a page or so, so I'll look for stuff of about that length.

**Comment by mdunca14** [comment]
Here's an article on a one page vision summary.  It recommends we focus on mentioning Core Values, Purpose, Brand, A Big Goal, Priorities, and Objectives 
https://blog.growthinstitute.com/scale-up-blueprint/one-page-vision-summary
